package com.cevher.keycloak;

import org.apache.http.HttpEntity;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;

import java.io.IOException;

public class Client {

    public static void postService(String data) throws IOException {

        // Do Http POST request to Service
        // Generated by ChatGPT

        CloseableHttpClient httpClient = HttpClients.createDefault();
        String uri = "http://host.docker.internal:8080/startRegistrationProcess";
        System.out.println("POST Event Data to: " + uri);

        try {
            HttpPost httpPost = new HttpPost(uri);

            // JSON payload
            StringEntity entity = new StringEntity(data, ContentType.APPLICATION_JSON);
            httpPost.setEntity(entity);

            CloseableHttpResponse response = httpClient.execute(httpPost);

            try {
                HttpEntity responseEntity = response.getEntity();
                if (responseEntity != null) {
                    String responseString = EntityUtils.toString(responseEntity, "UTF-8");
                    EntityUtils.consume(responseEntity);
                    System.out.println("Response status: " + response.getStatusLine().getStatusCode());
                    System.out.println("Response body: " + responseString);

                }


            } finally {
                response.close();
            }
        } catch (ClientProtocolException e) {

        } catch (IOException e) {

        } finally {
            httpClient.close();
        }
    }
}